[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.3.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[prune]
  go-tests = true
  unused-packages = true
