[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.3.0"

[prune]
  go-tests = true
  unused-packages = true
