[admission]
# bind_address is the "host:port" pair where the admission webhook is to be served.
bind_address = "0.0.0.0:8443"

[cluster]
# kubeconfig holds the path to the kubeconfig file to use (may be empty for in-cluster configuration).
kubeconfig = "/home/travelaudience/.kube/config"
# namespace holds the namespace where cloudsql-postgres-operator is deployed.
namespace = "cloudsql-postgres-operator"

[controllers]
# resync_period_seconds holds the resync period to use for the controllers, expressed in seconds.
resync_period_seconds = 180

[logging]
# level holds the log level to use (possible values: "trace", "debug", "info", "warn", "error", "fatal" and "panic").
level = "debug"

[gcp]
# admin_service_account_key_path holds the path to the file that contains credentials for an IAM Service Account with the "roles/cloudsql.admin" role.
admin_service_account_key_path = "admin-key.json"
# project_id holds the ID of the Google Cloud Platform project where cloudsql-postgres-operator is managing Cloud SQL instances.
project_id = "cloudsql-postgres-operator-123456"
