apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cloudsql-operator
  name: cloudsql-operator
  namespace: cloudsql-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cloudsql-operator
  name: cloudsql-operator
rules:
# Allow for performing leader election.
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - update
# Allow for emitting events.
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
# Allow for creating, reading, listing, updating and watching CustomResourceDefinition resources.
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cloudsql-operator
  name: cloudsql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudsql-operator
subjects:
  - kind: ServiceAccount
    name: cloudsql-operator
    namespace: cloudsql-operator
