apiVersion: v1
kind: Secret
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
data:
  admin-key.json: |
    __BASE64_ENCODED_ADMIN_KEY_JSON__
  client-key.json: |
    __BASE64_ENCODED_CLIENT_KEY_JSON__
