apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
data:
  config.toml: |
    [gcp]
    project_id = "__PROJECT_ID__"
