apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
spec:
  selector:
    app: cloudsql-postgres-operator
  ports:
    - name: admission
      port: 443
      targetPort: 443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudsql-postgres-operator
  template:
    metadata:
      labels:
        app: cloudsql-postgres-operator
    spec:
      containers:
      - name: cloudsql-postgres-operator
        image: "quay.io/travelaudience/cloudsql-postgres-operator:latest"
        imagePullPolicy: Always
        args:
        - /cloudsql-postgres-operator
        - --config-file
        - /config/config.toml
        ports:
        - name: admission
          containerPort: 443
        readinessProbe:
          httpGet:
            path: /healthz
            port: admission
            scheme: HTTPS
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
        - mountPath: /secret
          name: secret
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudsql-postgres-operator
      - name: secret
        secret:
          secretName: cloudsql-postgres-operator
      serviceAccountName: cloudsql-postgres-operator
