apiVersion: v1
kind: Secret
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
data:
  admin-key.json: |
    __BASE64_ENCODED_ADMIN_KEY_JSON__
  client-key.json: |
    __BASE64_ENCODED_CLIENT_KEY_JSON__
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
data:
  config.toml: |
    [gcp]
    project_id = "__PROJECT_ID__"
    [logging]
    level = "trace"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
spec:
  selector:
    app: cloudsql-postgres-operator
  ports:
  - name: admission
    port: 443
    targetPort: 443
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
spec:
  containers:
  - name: cloudsql-postgres-operator
    image: "gcr.io/__PROJECT_ID__/cloudsql-postgres-operator"
    imagePullPolicy: "__IMAGE_PULL_POLICY__"
    args:
    - /cloudsql-postgres-operator
    - --config-file
    - /config/config.toml
    ports:
    - name: admission
      containerPort: 443
    readinessProbe:
      httpGet:
        path: /healthz
        port: admission
        scheme: HTTPS
    volumeMounts:
    - mountPath: /config
      name: config
      readOnly: true
    - mountPath: /secret
      name: secret
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: cloudsql-postgres-operator
  - name: secret
    secret:
      secretName: cloudsql-postgres-operator
  serviceAccountName: cloudsql-postgres-operator
