apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: "gcr.io/__PROJECT_ID__/cloudsql-postgres-operator"
    docker:
      dockerfile: __TMP_DIR__/Dockerfile
deploy:
  kubectl:
    manifests:
    - docs/deployment/00-prereqs.yaml
    - __TMP_DIR__/deployment.yaml
profiles:
- name: gke
  build:
    googleCloudBuild:
      projectId: "__PROJECT_ID__"
- name: minikube
  build:
    local: {}
